import { readFile, writeFile } from "node:fs/promises";

const font = await readFile(new URL("../assets/JetBrainsMono-variable.woff2", import.meta.url));
await writeFile(new URL("../font.css", import.meta.url), `/* JetBrains Mono, SIL Open Font License. See assets/OFL.txt. Generated by scripts/embed-font.mjs. */
@font-face {
  font-family: "Herdr Mono";
  src: url("data:font/woff2;base64,${font.toString("base64")}") format("woff2");
  font-weight: 100 800;
  font-style: normal;
  font-display: swap;
}
`);
