"""Map Herdr palette data to BB roles; preserve shared terminal composition."""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'palettes/herdr.json').read_text())
families = [
 ('catppuccin','Catppuccin','catppuccin','catppuccin_latte','catppuccin-mocha','catppuccin-latte'),
 ('tokyo-night','Tokyo Night','tokyo_night','tokyo_night_day','tokyo-night','github-light'),
 ('dracula','Dracula','dracula',None,'dracula','github-light'),
 ('nord','Nord','nord',None,'nord','github-light'),
 ('gruvbox','Gruvbox','gruvbox','gruvbox_light','gruvbox-dark-medium','gruvbox-light-medium'),
 ('one','One','one_dark','one_light','one-dark-pro','one-light'),
 ('solarized','Solarized','solarized','solarized_light','solarized-dark','solarized-light'),
 ('kanagawa','Kanagawa','kanagawa','kanagawa_lotus','kanagawa-wave','kanagawa-lotus'),
 ('rose-pine','Rosé Pine','rose_pine','rose_pine_dawn','rose-pine','rose-pine-dawn'),
 ('vesper','Vesper','vesper',None,'vesper','github-light'),
]
def rgb(h): return [int(h[i:i+2],16) for i in (1,3,5)]
def mix(a,b,t):return '#'+''.join(f'{round(x*(1-t)+y*t):02x}' for x,y in zip(rgb(a),rgb(b)))
def lum(c):
 v=[x/255 for x in rgb(c)];v=[x/12.92 if x<=.04045 else ((x+.055)/1.055)**2.4 for x in v]
 return sum(x*y for x,y in zip(v,[.2126,.7152,.0722]))
def ratio(a,b):
 x,y=sorted([lum(a),lum(b)]);return (y+.05)/(x+.05)
def readable(color,backs,target=5.5):
 toward='#000000' if sum(lum(b) for b in backs)/len(backs)>.4 else '#ffffff'
 for i in range(101):
  c=mix(color,toward,i/100)
  if min(ratio(c,b) for b in backs)>=target:return c
 raise ValueError('Cannot achieve contrast')
def companion(c):return max(['#000000','#ffffff'],key=lambda x:ratio(c,x))
def tokens(p,light,adapted=False):
 bg=p['panel_bg'];ink=p['text']
 if adapted:bg=mix(p['mauve'],'#ffffff',.96);ink=mix(p['panel_bg'],'#000000',.25)
 sidebar=mix(bg,ink,.035);popover=mix(bg,ink,.025);backs=[bg,sidebar,popover]
 ink=readable(ink,backs,7)
 accent=readable(p['accent'],backs)
 colors={k:readable(p[k],backs) for k in ['green','red','yellow','blue','teal','mauve','peach']}
 d={'canvas':bg,'ink':ink,'background':'var(--canvas)','foreground':'var(--ink)',
 'card':bg,'card-foreground':ink,'popover':popover,'popover-foreground':ink,
 'primary':accent,'primary-foreground':companion(accent),'ring':accent,
 'timeline-accent':colors['blue'],'file-accent':colors['teal'],
 'muted-foreground':readable(p['subtext0'],backs,6),
 'readback-foreground':readable(p['overlay1'],backs,5.2),
 'subtle-foreground':readable(p['overlay0'],backs,4.8),
 'sidebar':sidebar,'sidebar-foreground':ink,'sidebar-accent-foreground':ink,
 'secondary-foreground':ink,'accent-foreground':ink,
 'secondary':mix(bg,ink,.06),'accent':mix(bg,ink,.06),'muted':mix(bg,ink,.09),
 'surface-recessed-solid':sidebar,'surface-recessed-soft-solid':mix(bg,ink,.025),
 'surface-raised-solid':popover,'sidebar-accent':mix(bg,accent,.10),
 'border':mix(bg,ink,.2),'border-hairline':mix(bg,ink,.17),
 'border-seam':mix(bg,ink,.10),'border-seam-vertical':'var(--border-seam)',
 'sidebar-border':mix(bg,ink,.15),'input':mix(bg,ink,.3),
 'destructive':colors['red'],'destructive-text':colors['red'],
 'destructive-foreground':companion(colors['red']),
 'warning':colors['yellow'],'warning-text':colors['yellow'],'attention':colors['peach'],
 'success':colors['green'],'diff-added':colors['green'],'diff-removed':colors['red'],'pr-merged':colors['mauve']}
 ansi=[p['surface0'],colors['red'],colors['green'],colors['yellow'],colors['blue'],colors['mauve'],colors['teal'],ink,p['overlay0'],colors['red'],colors['green'],colors['yellow'],colors['blue'],colors['mauve'],colors['teal'],ink]
 for i,c in enumerate(ansi):d[f'ansi-{i}']=c;d[f'ansi-bg-fg-{i}']=companion(c)
 return d,backs
base=(ROOT/'themes/lavender.css').read_text()
blocks=re.findall(r'(?:\.light|\.dark)\s*\{(.*?)\n\}',base,re.S)
entries=[];report=[]
for id,label,dark,light,code_dark,code_light in families:
 out=['/* Generated by scripts/generate-palettes.py. Herdr palette data with BB\n   contrast and surface adaptations. See palettes/README.md. */']
 swatches={}
 for mode,key in [('light',light or dark),('dark',dark)]:
  mapped,backs=tokens(data[key],mode=='light',mode=='light' and light is None)
  source=blocks[0 if mode=='light' else 1].replace('--herdr-theme-id: lavender;', f'--herdr-theme-id: {id};')
  source=re.sub(r'/\*.*?\*/','',source,flags=re.S)
  source=re.sub(r'(--([\w-]+):)\s*([^;]+);',lambda m:m[1]+' '+mapped.get(m[2],m[3].strip())+';',source)
  out.append((':root, .light' if mode=='light' else '.dark')+' {'+source+'\n}')
  swatches[mode]=[mapped[k] for k in ['canvas','sidebar','primary','success','attention']]
  for role in ['ink','muted-foreground','readback-foreground','subtle-foreground','primary','success','warning-text','destructive-text','attention']:
   r=min(ratio(mapped[role],b) for b in backs)
   assert r>=4.5,(id,mode,role,r)
   report.append(f'{id:12} {mode:5} {role:22} {r:.2f}')
 (ROOT/f'themes/{id}.css').write_text('\n\n'.join(out)+'\n')
 entries.append({'id':id,'name':label,'adaptedLight':light is None,'swatches':swatches})
manifest=json.loads((ROOT/'package.json').read_text())
manifest['bb']['themes']=manifest['bb']['themes'][:1]+[{'id':id,'name':'Herdr '+label,'description':label+' with Herdr terminal composition.'+(' Light is a BB adaptation.' if light is None else ''),'css':f'./themes/{id}.css','codeTheme':{'dark':cd,'light':cl}} for id,label,dark,light,cd,cl in families]
(ROOT/'package.json').write_text(json.dumps(manifest,indent=2)+'\n')
lavender={mode:dict(re.findall(r'--([\w-]+):\s*([^;]+);', block)) for mode,block in zip(['light','dark'],blocks)}
entries.insert(0,{'id':'lavender','name':'Lavender','adaptedLight':False,'swatches':{mode:[d[k].strip() for k in ['canvas','sidebar','primary','success','attention']] for mode,d in lavender.items()}})
(ROOT/'palettes/catalog.json').write_text(json.dumps(entries,indent=2)+'\n')
(ROOT/'design/palette-contrast.txt').write_text('\n'.join(report)+'\n')
print(f'Generated {len(families)} families; {len(report)} text contrast checks passed.')
